2024-01-16 04:18:38,667 - pygad.pygad - ERROR - expected str, bytes or os.PathLike object, not bool
Traceback (most recent call last):
  File "/home/pavel/dev/diplom/tssproblem/venv/lib/python3.11/site-packages/pygad/pygad.py", line 1796, in cal_pop_fitness
    for index, fitness in zip(solutions_to_submit_indices, executor.map(self.fitness_func, [self]*len(solutions_to_submit_indices), solutions_to_submit, solutions_to_submit_indices)):
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pavel/dev/diplom/tssproblem/gen.py", line 67, in <lambda>
    ff_wrapper = lambda ga_instance, solution, solution_idx: fitness_func(ga_instance,
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pavel/dev/diplom/tssproblem/gen.py", line 52, in fitness_func
    process = subprocess.Popen(command)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1883, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not bool
